[package]
name = "minimarkdown"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
name = "minimarkdown"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "minimarkdown"
path = "src/main.rs"
test = false
bench = false

[dependencies]
quick-xml = "0.38"
zip = { version = "4", default-features = false, features = ["deflate"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tempfile = "3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
